verbose: false
max_depth: 20
min_depth: 3
max_wait: 20
min_wait: 3
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
root_urls:
  - https://www.google.com
  - https://www.blogger.com
  - https://www.youtube.com
  - https://www.linkedin.com
  - https://www.support.google.com
  - https://www.cloudflare.com
  - https://www.microsoft.com
  - https://www.apple.com
  - https://www.en.wikipedia.org
  - https://www.play.google.com
  - https://www.wordpress.org
  - https://www.docs.google.com
  - https://www.mozilla.org
  - https://www.maps.google.com
  - https://www.youtu.be
  - https://www.drive.google.com
  - https://www.bp.blogspot.com
  - https://www.sites.google.com
  - https://www.googleusercontent.com
  - https://www.accounts.google.com
  - https://www.t.me
  - https://www.europa.eu
  - https://www.plus.google.com
  - https://www.whatsapp.com
  - https://www.adobe.com
  - https://www.facebook.com
  - https://www.policies.google.com
  - https://www.uol.com.br
  - https://www.istockphoto.com
  - https://www.vimeo.com
  - https://www.vk.com
  - https://www.github.com
  - https://www.amazon.com
  - https://www.search.google.com
  - https://www.bbc.co.uk
  - https://www.google.de
  - https://www.live.com
  - https://www.gravatar.com
  - https://www.nih.gov
  - https://www.dan.com
  - https://www.files.wordpress.com
  - https://www.yahoo.com
  - https://www.cnn.com
  - https://www.dropbox.com
  - https://www.wikimedia.org
  - https://www.creativecommons.org
  - https://www.google.com.br
  - https://www.line.me
  - https://www.googleblog.com
  - https://www.opera.com
  - https://www.es.wikipedia.org
  - https://www.globo.com
  - https://www.brandbucket.com
  - https://www.myspace.com
  - https://www.slideshare.net
  - https://www.paypal.com
  - https://www.tiktok.com
  - https://www.netvibes.com
  - https://www.theguardian.com
  - https://www.who.int
  - https://www.goo.gl
  - https://www.medium.com
  - https://www.tools.google.com
  - https://www.draft.blogger.com
  - https://www.pt.wikipedia.org
  - https://www.fr.wikipedia.org
  - https://www.weebly.com
  - https://www.news.google.com
  - https://www.developers.google.com
  - https://www.w3.org
  - https://www.mail.google.com
  - https://www.gstatic.com
  - https://www.jimdofree.com
  - https://www.cpanel.net
  - https://www.imdb.com
  - https://www.wa.me
  - https://www.feedburner.com
  - https://www.enable-javascript.com
  - https://www.nytimes.com
  - https://www.workspace.google.com
  - https://www.ok.ru
  - https://www.google.es
  - https://www.dailymotion.com
  - https://www.afternic.com
  - https://www.bloomberg.com
  - https://www.amazon.de
  - https://www.photos.google.com
  - https://www.wiley.com
  - https://www.aliexpress.com
  - https://www.indiatimes.com
  - https://www.youronlinechoices.com
  - https://www.elpais.com
  - https://www.tinyurl.com
  - https://www.yadi.sk
  - https://www.spotify.com
  - https://www.huffpost.com
  - https://www.ru.wikipedia.org
  - https://www.google.fr
  - https://www.webmd.com
  - https://www.samsung.com
  - https://www.independent.co.uk
  - https://www.amazon.co.jp
  - https://www.get.google.com
  - https://www.amazon.co.uk
  - https://www.4shared.com
  - https://www.telegram.me
  - https://www.planalto.gov.br
  - https://www.businessinsider.com
  - https://www.ig.com.br
  - https://www.issuu.com
  - https://www.gov.br
  - https://www.wsj.com
  - https://www.hugedomains.com
  - https://www.picasaweb.google.com
  - https://www.usatoday.com
  - https://www.scribd.com
  - https://www.gov.uk
  - https://www.storage.googleapis.com
  - https://www.huffingtonpost.com
  - https://www.bbc.com
  - https://www.estadao.com.br
  - https://www.nature.com
  - https://www.mediafire.com
  - https://www.washingtonpost.com
  - https://www.forms.gle
  - https://www.namecheap.com
  - https://www.forbes.com
  - https://www.mirror.co.uk
  - https://www.soundcloud.com
  - https://www.fb.com
  - https://www.marketingplatform.google....
  - https://www.domainmarket.com
  - https://www.ytimg.com
  - https://www.terra.com.br
  - https://www.google.co.uk
  - https://www.shutterstock.com
  - https://www.dailymail.co.uk
  - https://www.reg.ru
  - https://www.t.co
  - https://www.cdc.gov
  - https://www.thesun.co.uk
  - https://www.wp.com
  - https://www.cnet.com
  - https://www.instagram.com
  - https://www.researchgate.net
  - https://www.google.it
  - https://www.fandom.com
  - https://www.office.com
  - https://www.list-manage.com
  - https://www.msn.com
  - https://www.un.org
  - https://www.mail.ru
  - https://www.news.com.au
  - https://www.mailchimp.com
  - https://www.stores.jp
  - https://www.nhk.or.jp
blacklist:
  - https://t.co
  - play.google
  - instagram.com
  - t.umblr.com
  - messenger.com
  - itunes.apple.com
  - l.facebook.com
  - bit.ly
  - mediawiki
  - .css
  - .ico
  - .xml
  - intent/tweet
  - twitter.com/share
  - signup
  - login
  - dialog/feed?
  - .png
  - .jpg
  - .json
  - .svg
  - .gif
  - .woff2
  - zendesk
  - clickserve
