name: Build OCI compatible container image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Install pack CLI
        run: |
          curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.35.1/pack-v0.35.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          pack build ${{ secrets.DOCKERHUB_USERNAME }}/webtraffic:latest \
            --builder heroku/builder:24 \
            --env BP_KEEP_FILES="*.yaml" \
            --env CGO_ENABLED=0 \
            --env GOARCH=arm64 \
            --env GOOS=linux \
            --platform=linux/arm64 \
            --publish
